// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.5.1
// source: prime_decomposition/prime_decompositionpb/prime_decomposition.proto

package prime_decompositionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrimeNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *PrimeNumber) Reset() {
	*x = PrimeNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeNumber) ProtoMessage() {}

func (x *PrimeNumber) ProtoReflect() protoreflect.Message {
	mi := &file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeNumber.ProtoReflect.Descriptor instead.
func (*PrimeNumber) Descriptor() ([]byte, []int) {
	return file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_rawDescGZIP(), []int{0}
}

func (x *PrimeNumber) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type PrimeNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrimeNumber *PrimeNumber `protobuf:"bytes,1,opt,name=prime_number,json=primeNumber,proto3" json:"prime_number,omitempty"`
}

func (x *PrimeNumberRequest) Reset() {
	*x = PrimeNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeNumberRequest) ProtoMessage() {}

func (x *PrimeNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeNumberRequest.ProtoReflect.Descriptor instead.
func (*PrimeNumberRequest) Descriptor() ([]byte, []int) {
	return file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_rawDescGZIP(), []int{1}
}

func (x *PrimeNumberRequest) GetPrimeNumber() *PrimeNumber {
	if x != nil {
		return x.PrimeNumber
	}
	return nil
}

type PrimeNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *PrimeNumberResponse) Reset() {
	*x = PrimeNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeNumberResponse) ProtoMessage() {}

func (x *PrimeNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeNumberResponse.ProtoReflect.Descriptor instead.
func (*PrimeNumberResponse) Descriptor() ([]byte, []int) {
	return file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_rawDescGZIP(), []int{2}
}

func (x *PrimeNumberResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_prime_decomposition_prime_decompositionpb_prime_decomposition_proto protoreflect.FileDescriptor

var file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_rawDesc = []byte{
	0x0a, 0x43, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x65, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x69, 0x6d,
	0x65, 0x5f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x65, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x25, 0x0a, 0x0b, 0x50, 0x72,
	0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0x59, 0x0a, 0x12, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x0c, 0x70, 0x72, 0x69, 0x6d, 0x65,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x0b, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2d, 0x0a, 0x13,
	0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x81, 0x01, 0x0a, 0x12,
	0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x6b, 0x0a, 0x12, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x6d,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x65,
	0x5f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50,
	0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x28, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42,
	0x2b, 0x5a, 0x29, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x65, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_rawDescOnce sync.Once
	file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_rawDescData = file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_rawDesc
)

func file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_rawDescGZIP() []byte {
	file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_rawDescOnce.Do(func() {
		file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_rawDescData = protoimpl.X.CompressGZIP(file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_rawDescData)
	})
	return file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_rawDescData
}

var file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_goTypes = []interface{}{
	(*PrimeNumber)(nil),         // 0: prime_decomposition.PrimeNumber
	(*PrimeNumberRequest)(nil),  // 1: prime_decomposition.PrimeNumberRequest
	(*PrimeNumberResponse)(nil), // 2: prime_decomposition.PrimeNumberResponse
}
var file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_depIdxs = []int32{
	0, // 0: prime_decomposition.PrimeNumberRequest.prime_number:type_name -> prime_decomposition.PrimeNumber
	1, // 1: prime_decomposition.PrimeNumberService.PrimeDecomposition:input_type -> prime_decomposition.PrimeNumberRequest
	2, // 2: prime_decomposition.PrimeNumberService.PrimeDecomposition:output_type -> prime_decomposition.PrimeNumberResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_init() }
func file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_init() {
	if File_prime_decomposition_prime_decompositionpb_prime_decomposition_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_goTypes,
		DependencyIndexes: file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_depIdxs,
		MessageInfos:      file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_msgTypes,
	}.Build()
	File_prime_decomposition_prime_decompositionpb_prime_decomposition_proto = out.File
	file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_rawDesc = nil
	file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_goTypes = nil
	file_prime_decomposition_prime_decompositionpb_prime_decomposition_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrimeNumberServiceClient is the client API for PrimeNumberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimeNumberServiceClient interface {
	// Server Streaming
	PrimeDecomposition(ctx context.Context, in *PrimeNumberRequest, opts ...grpc.CallOption) (PrimeNumberService_PrimeDecompositionClient, error)
}

type primeNumberServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeNumberServiceClient(cc grpc.ClientConnInterface) PrimeNumberServiceClient {
	return &primeNumberServiceClient{cc}
}

func (c *primeNumberServiceClient) PrimeDecomposition(ctx context.Context, in *PrimeNumberRequest, opts ...grpc.CallOption) (PrimeNumberService_PrimeDecompositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrimeNumberService_serviceDesc.Streams[0], "/prime_decomposition.PrimeNumberService/PrimeDecomposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &primeNumberServicePrimeDecompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrimeNumberService_PrimeDecompositionClient interface {
	Recv() (*PrimeNumberResponse, error)
	grpc.ClientStream
}

type primeNumberServicePrimeDecompositionClient struct {
	grpc.ClientStream
}

func (x *primeNumberServicePrimeDecompositionClient) Recv() (*PrimeNumberResponse, error) {
	m := new(PrimeNumberResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrimeNumberServiceServer is the server API for PrimeNumberService service.
type PrimeNumberServiceServer interface {
	// Server Streaming
	PrimeDecomposition(*PrimeNumberRequest, PrimeNumberService_PrimeDecompositionServer) error
}

// UnimplementedPrimeNumberServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPrimeNumberServiceServer struct {
}

func (*UnimplementedPrimeNumberServiceServer) PrimeDecomposition(*PrimeNumberRequest, PrimeNumberService_PrimeDecompositionServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeDecomposition not implemented")
}

func RegisterPrimeNumberServiceServer(s *grpc.Server, srv PrimeNumberServiceServer) {
	s.RegisterService(&_PrimeNumberService_serviceDesc, srv)
}

func _PrimeNumberService_PrimeDecomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrimeNumberServiceServer).PrimeDecomposition(m, &primeNumberServicePrimeDecompositionServer{stream})
}

type PrimeNumberService_PrimeDecompositionServer interface {
	Send(*PrimeNumberResponse) error
	grpc.ServerStream
}

type primeNumberServicePrimeDecompositionServer struct {
	grpc.ServerStream
}

func (x *primeNumberServicePrimeDecompositionServer) Send(m *PrimeNumberResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PrimeNumberService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prime_decomposition.PrimeNumberService",
	HandlerType: (*PrimeNumberServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeDecomposition",
			Handler:       _PrimeNumberService_PrimeDecomposition_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "prime_decomposition/prime_decompositionpb/prime_decomposition.proto",
}
